from __future__ import annotations

from typing import Any


def build_torch_global_catalog(context: Any) -> dict[str, Any]:
    ModelSpec = context.ModelSpec
    _TORCH_COMMON_DEFAULTS = context._TORCH_COMMON_DEFAULTS
    _TORCH_COMMON_PARAM_HELP = context._TORCH_COMMON_PARAM_HELP
    _factory_torch_timexer_global = context._factory_torch_timexer_global
    torch_autoformer_global_forecaster = context.torch_autoformer_global_forecaster
    torch_crossformer_global_forecaster = context.torch_crossformer_global_forecaster
    torch_deepar_global_forecaster = context.torch_deepar_global_forecaster
    torch_dilated_rnn_global_forecaster = context.torch_dilated_rnn_global_forecaster
    torch_dlinear_global_forecaster = context.torch_dlinear_global_forecaster
    torch_esrnn_global_forecaster = context.torch_esrnn_global_forecaster
    torch_etsformer_global_forecaster = context.torch_etsformer_global_forecaster
    torch_fedformer_global_forecaster = context.torch_fedformer_global_forecaster
    torch_fnet_global_forecaster = context.torch_fnet_global_forecaster
    torch_gmlp_global_forecaster = context.torch_gmlp_global_forecaster
    torch_hyena_global_forecaster = context.torch_hyena_global_forecaster
    torch_inception_global_forecaster = context.torch_inception_global_forecaster
    torch_informer_global_forecaster = context.torch_informer_global_forecaster
    torch_itransformer_global_forecaster = context.torch_itransformer_global_forecaster
    torch_kan_global_forecaster = context.torch_kan_global_forecaster
    torch_lstnet_global_forecaster = context.torch_lstnet_global_forecaster
    torch_mamba_global_forecaster = context.torch_mamba_global_forecaster
    torch_nbeats_global_forecaster = context.torch_nbeats_global_forecaster
    torch_nhits_global_forecaster = context.torch_nhits_global_forecaster
    torch_nlinear_global_forecaster = context.torch_nlinear_global_forecaster
    torch_nonstationary_transformer_global_forecaster = context.torch_nonstationary_transformer_global_forecaster
    torch_patchtst_global_forecaster = context.torch_patchtst_global_forecaster
    torch_pyraformer_global_forecaster = context.torch_pyraformer_global_forecaster
    torch_resnet1d_global_forecaster = context.torch_resnet1d_global_forecaster
    torch_retnet_global_forecaster = context.torch_retnet_global_forecaster
    torch_rwkv_global_forecaster = context.torch_rwkv_global_forecaster
    torch_scinet_global_forecaster = context.torch_scinet_global_forecaster
    torch_seq2seq_global_forecaster = context.torch_seq2seq_global_forecaster
    torch_ssm_global_forecaster = context.torch_ssm_global_forecaster
    torch_tcn_global_forecaster = context.torch_tcn_global_forecaster
    torch_tft_global_forecaster = context.torch_tft_global_forecaster
    torch_tide_global_forecaster = context.torch_tide_global_forecaster
    torch_timesnet_global_forecaster = context.torch_timesnet_global_forecaster
    torch_transformer_encdec_global_forecaster = context.torch_transformer_encdec_global_forecaster
    torch_tsmixer_global_forecaster = context.torch_tsmixer_global_forecaster
    torch_wavenet_global_forecaster = context.torch_wavenet_global_forecaster
    CONTEXT_LENGTH_PARAM_HELP = "Context window length (encoder length)"
    OPTIONAL_X_COLS_PARAM_HELP = (
        "Optional covariate columns from long_df (comma-separated)"
    )
    ADD_TIME_FEATURES_PARAM_HELP = "Add built-in time features from ds (true/false)"
    SAMPLE_STEP_PARAM_HELP = "Stride when generating training windows (>=1)"
    ATTENTION_HEADS_PARAM_HELP = "Attention heads"
    MODEL_DIMENSION_PARAM_HELP = "Model dimension"
    TRANSFORMER_MODEL_DIMENSION_PARAM_HELP = "Transformer model dimension"
    ENCODER_LAYERS_PARAM_HELP = "Encoder layers"
    TRANSFORMER_FFN_DIM_PARAM_HELP = "Transformer FFN dimension"
    ID_EMB_DIM_PARAM_HELP = "Series-id embedding dim (panel/global models)"
    DROPOUT_PROBABILITY_PARAM_HELP = "Dropout probability in [0,1)"
    QUANTILES_PARAM_HELP = (
        "Optional quantiles for pinball loss, e.g. 0.1,0.5,0.9 (adds yhat_pXX columns)"
    )
    MAX_TRAIN_SIZE_PARAM_HELP = (
        "Optional per-series rolling training window length (None for expanding)"
    )
    CONV1D_KERNEL_SIZE_PARAM_HELP = "Conv1D kernel size (>=1)"
    NUM_RESIDUAL_BLOCKS_PARAM_HELP = "Number of residual blocks"
    RNN_HIDDEN_SIZE_PARAM_HELP = "RNN hidden size"
    STACKED_RNN_LAYERS_PARAM_HELP = "Number of stacked RNN layers"
    RNN_DROPOUT_PARAM_HELP = "Dropout probability in [0,1) (only if num_layers>1)"
    RNN_CELL_PARAM_HELP = "RNN cell: lstm, gru"
    ATTENTION_MODE_PARAM_HELP = "Attention: none, bahdanau"
    TEACHER_FORCING_PARAM_HELP = "Teacher forcing ratio at the start of training"
    TEACHER_FORCING_FINAL_PARAM_HELP = (
        "Teacher forcing ratio at the end of training (None keeps it constant)"
    )
    return {
    "torch-tft-global": ModelSpec(
        key="torch-tft-global",
        description="Torch Temporal Fusion Transformer (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_tft_global_forecaster,
        default_params={
            "context_length": 48,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "lstm_layers": 1,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": "Embedding dimension",
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "lstm_layers": "Number of LSTM layers",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-timexer-global": ModelSpec(
        key="torch-timexer-global",
        description="Torch TimeXer-style exogenous-aware transformer (lite) trained globally across panel series. Requires PyTorch.",
        factory=_factory_torch_timexer_global,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": "Required covariate columns from long_df (comma-separated)",
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "nhead": "Number of attention heads",
            "num_layers": "Number of encoder / cross-attention blocks",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
        capability_overrides={"requires_future_covariates": True},
    ),
    "torch-retnet-global": ModelSpec(
        key="torch-retnet-global",
        description="Torch RetNet-style retention network (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_retnet_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "ffn_dim": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "nhead": "Number of retention heads",
            "num_layers": "Number of stacked retention blocks",
            "ffn_dim": "Feed-forward hidden width inside each retention block",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-informer-global": ModelSpec(
        key="torch-informer-global",
        description="Torch Informer (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_informer_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "dim_feedforward": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": TRANSFORMER_MODEL_DIMENSION_PARAM_HELP,
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "num_layers": ENCODER_LAYERS_PARAM_HELP,
            "dim_feedforward": TRANSFORMER_FFN_DIM_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-autoformer-global": ModelSpec(
        key="torch-autoformer-global",
        description="Torch Autoformer (lite) with series decomposition, trained globally across panel series. Requires PyTorch.",
        factory=torch_autoformer_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "dim_feedforward": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "ma_window": 7,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": TRANSFORMER_MODEL_DIMENSION_PARAM_HELP,
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "num_layers": ENCODER_LAYERS_PARAM_HELP,
            "dim_feedforward": TRANSFORMER_FFN_DIM_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "ma_window": "Moving-average window for trend/seasonal decomposition",
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-fedformer-global": ModelSpec(
        key="torch-fedformer-global",
        description="Torch FEDformer-style (lite) decomposition + frequency mixing, trained globally across panel series. Requires PyTorch.",
        factory=torch_fedformer_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_layers": 2,
            "ffn_dim": 256,
            "modes": 16,
            "ma_window": 7,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "num_layers": "Number of frequency-mixing blocks",
            "ffn_dim": "FFN hidden dimension",
            "modes": "Number of low-frequency FFT modes to keep (>=1)",
            "ma_window": "Moving-average window for trend extraction (>=1)",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-nonstationary-transformer-global": ModelSpec(
        key="torch-nonstationary-transformer-global",
        description="Torch Non-stationary Transformer (lite) with RevIN + de-stationary attention factors, trained globally across panel series. Requires PyTorch.",
        factory=torch_nonstationary_transformer_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "dim_feedforward": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": TRANSFORMER_MODEL_DIMENSION_PARAM_HELP,
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "num_layers": ENCODER_LAYERS_PARAM_HELP,
            "dim_feedforward": TRANSFORMER_FFN_DIM_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-patchtst-global": ModelSpec(
        key="torch-patchtst-global",
        description="Torch PatchTST-style (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_patchtst_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "dim_feedforward": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "patch_len": 16,
            "stride": 8,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": TRANSFORMER_MODEL_DIMENSION_PARAM_HELP,
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "num_layers": ENCODER_LAYERS_PARAM_HELP,
            "dim_feedforward": TRANSFORMER_FFN_DIM_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "patch_len": "Patch length over (context+horizon) tokens",
            "stride": "Patch stride (>=1)",
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-crossformer-global": ModelSpec(
        key="torch-crossformer-global",
        description="Torch Crossformer-style (lite) multi-scale segmented Transformer encoder trained globally across panel series. Requires PyTorch.",
        factory=torch_crossformer_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "dim_feedforward": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "segment_len": 16,
            "stride": 16,
            "num_scales": 3,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": TRANSFORMER_MODEL_DIMENSION_PARAM_HELP,
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "num_layers": ENCODER_LAYERS_PARAM_HELP,
            "dim_feedforward": TRANSFORMER_FFN_DIM_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "segment_len": "Base segment length over (context+horizon) tokens",
            "stride": "Base segment stride over (context+horizon) tokens",
            "num_scales": "Number of scales (>=1)",
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-pyraformer-global": ModelSpec(
        key="torch-pyraformer-global",
        description="Torch Pyraformer-style (lite) pyramid-pooled segmented Transformer encoder trained globally across panel series. Requires PyTorch.",
        factory=torch_pyraformer_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "dim_feedforward": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "segment_len": 16,
            "stride": 16,
            "num_levels": 3,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": TRANSFORMER_MODEL_DIMENSION_PARAM_HELP,
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "num_layers": ENCODER_LAYERS_PARAM_HELP,
            "dim_feedforward": TRANSFORMER_FFN_DIM_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "segment_len": "Segment length at level-0 over (context+horizon) tokens",
            "stride": "Segment stride at level-0 over (context+horizon) tokens",
            "num_levels": "Number of pyramid levels (>=1)",
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-tsmixer-global": ModelSpec(
        key="torch-tsmixer-global",
        description="Torch TSMixer-style (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_tsmixer_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_blocks": 4,
            "token_mixing_hidden": 128,
            "channel_mixing_hidden": 128,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": "Mixer model dimension",
            "num_blocks": "Number of mixer blocks",
            "token_mixing_hidden": "Hidden size for token-mixing MLP",
            "channel_mixing_hidden": "Hidden size for channel-mixing MLP",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-itransformer-global": ModelSpec(
        key="torch-itransformer-global",
        description="Torch iTransformer-style (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_itransformer_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "dim_feedforward": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": TRANSFORMER_MODEL_DIMENSION_PARAM_HELP,
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "num_layers": ENCODER_LAYERS_PARAM_HELP,
            "dim_feedforward": TRANSFORMER_FFN_DIM_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-timesnet-global": ModelSpec(
        key="torch-timesnet-global",
        description="Torch TimesNet-style (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_timesnet_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_layers": 2,
            "top_k": 3,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": "Embedding dimension",
            "num_layers": "Number of TimesBlocks",
            "top_k": "Number of dominant periods to use (>=1)",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-tcn-global": ModelSpec(
        key="torch-tcn-global",
        description="Torch TCN (causal dilated Conv1D) trained globally across panel series. Requires PyTorch.",
        factory=torch_tcn_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "channels": (64, 64, 64),
            "kernel_size": 3,
            "dilation_base": 2,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "channels": "Channel sizes for TCN layers (comma-separated)",
            "kernel_size": CONV1D_KERNEL_SIZE_PARAM_HELP,
            "dilation_base": "Dilation base (>=1), layer i uses dilation_base**i",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-nbeats-global": ModelSpec(
        key="torch-nbeats-global",
        description="Torch N-BEATS-style (generic) trained globally across panel series. Requires PyTorch.",
        factory=torch_nbeats_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "num_blocks": 3,
            "num_layers": 2,
            "layer_width": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "num_blocks": NUM_RESIDUAL_BLOCKS_PARAM_HELP,
            "num_layers": "MLP layers per block",
            "layer_width": "Hidden width of MLP layers",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-nhits-global": ModelSpec(
        key="torch-nhits-global",
        description="Torch N-HiTS-style (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_nhits_global_forecaster,
        default_params={
            "context_length": 192,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "pool_sizes": (1, 2, 4),
            "num_blocks": 6,
            "num_layers": 2,
            "layer_width": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "pool_sizes": "Avg-pool downsample factors (comma-separated, <=context_length)",
            "num_blocks": NUM_RESIDUAL_BLOCKS_PARAM_HELP,
            "num_layers": "MLP layers per block",
            "layer_width": "Hidden width of MLP layers",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-tide-global": ModelSpec(
        key="torch-tide-global",
        description="Torch TiDE-style (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_tide_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "hidden_size": 128,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": "Latent model dimension",
            "hidden_size": "Hidden size for encoder/decoder MLPs",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-wavenet-global": ModelSpec(
        key="torch-wavenet-global",
        description="Torch WaveNet-style gated dilated CNN trained globally across panel series. Requires PyTorch.",
        factory=torch_wavenet_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "channels": 32,
            "num_layers": 6,
            "kernel_size": 2,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "channels": "Hidden channels in WaveNet stack",
            "num_layers": "Number of dilated convolution layers",
            "kernel_size": CONV1D_KERNEL_SIZE_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-resnet1d-global": ModelSpec(
        key="torch-resnet1d-global",
        description="Torch ResNet-1D Conv1D model trained globally across panel series. Requires PyTorch.",
        factory=torch_resnet1d_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "channels": 32,
            "num_blocks": 4,
            "kernel_size": 3,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "channels": "Conv1D channels",
            "num_blocks": NUM_RESIDUAL_BLOCKS_PARAM_HELP,
            "kernel_size": CONV1D_KERNEL_SIZE_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-inception-global": ModelSpec(
        key="torch-inception-global",
        description="Torch InceptionTime-style Conv1D model trained globally across panel series. Requires PyTorch.",
        factory=torch_inception_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "channels": 32,
            "num_blocks": 3,
            "kernel_sizes": (3, 5, 7),
            "bottleneck_channels": 16,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "channels": "Conv1D channels",
            "num_blocks": "Number of inception blocks",
            "kernel_sizes": "Kernel sizes (comma-separated)",
            "bottleneck_channels": "Bottleneck channels inside inception blocks",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-lstnet-global": ModelSpec(
        key="torch-lstnet-global",
        description="Torch LSTNet-style (CNN+GRU+skip+highway, lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_lstnet_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "cnn_channels": 16,
            "kernel_size": 6,
            "rnn_hidden": 32,
            "skip": 24,
            "highway_window": 24,
            "id_emb_dim": 8,
            "dropout": 0.2,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "cnn_channels": "Conv1D output channels",
            "kernel_size": CONV1D_KERNEL_SIZE_PARAM_HELP,
            "rnn_hidden": "GRU hidden size",
            "skip": "Skip length for skip-GRU (0 disables)",
            "highway_window": "Highway window length over the context y channel (0 disables)",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-fnet-global": ModelSpec(
        key="torch-fnet-global",
        description="Torch FNet-style (FFT token mixing, lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_fnet_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_layers": 4,
            "dim_feedforward": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "num_layers": "Number of FNet layers",
            "dim_feedforward": "FFN hidden dimension",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-gmlp-global": ModelSpec(
        key="torch-gmlp-global",
        description="Torch gMLP-style (spatial gating, lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_gmlp_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_layers": 4,
            "ffn_dim": 128,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "num_layers": "Number of gMLP layers",
            "ffn_dim": "FFN dimension inside gMLP",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-ssm-global": ModelSpec(
        key="torch-ssm-global",
        description="Torch diagonal state-space model (SSM, lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_ssm_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_layers": 4,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "num_layers": "Number of SSM blocks",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-mamba-global": ModelSpec(
        key="torch-mamba-global",
        description="Torch Mamba-style selective SSM (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_mamba_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_layers": 4,
            "conv_kernel": 3,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "num_layers": "Number of stacked Mamba blocks",
            "conv_kernel": "Causal depthwise conv kernel size (>=1)",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-rwkv-global": ModelSpec(
        key="torch-rwkv-global",
        description="Torch RWKV-style time-mix + channel-mix (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_rwkv_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_layers": 4,
            "ffn_dim": 128,
            "id_emb_dim": 8,
            "dropout": 0.0,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "num_layers": "Number of stacked RWKV blocks",
            "ffn_dim": "Channel-mix hidden size",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-hyena-global": ModelSpec(
        key="torch-hyena-global",
        description="Torch Hyena-style long convolution (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_hyena_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_layers": 4,
            "ffn_dim": 128,
            "kernel_size": 64,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "num_layers": "Number of Hyena blocks",
            "ffn_dim": "Channel-mixing FFN hidden size",
            "kernel_size": "Depthwise causal conv kernel size (>=1)",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-dilated-rnn-global": ModelSpec(
        key="torch-dilated-rnn-global",
        description="Torch Dilated RNN (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_dilated_rnn_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "cell": "gru",
            "d_model": 64,
            "num_layers": 3,
            "dilation_base": 2,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "cell": "Recurrent cell: gru or lstm",
            "d_model": "Hidden size / model dimension",
            "num_layers": "Number of dilated recurrent layers",
            "dilation_base": "Dilation base (>=2); dilations are base^layer_index",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-kan-global": ModelSpec(
        key="torch-kan-global",
        description="Torch KAN-style spline MLP (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_kan_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_layers": 2,
            "grid_size": 16,
            "grid_range": 2.0,
            "linear_skip": True,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": "Hidden width of the KAN network",
            "num_layers": "Number of KAN spline layers",
            "grid_size": "Number of spline knots (>=4)",
            "grid_range": "Spline grid range (+/- range) in normalized y units",
            "linear_skip": "Add a linear skip connection per layer (true/false)",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-scinet-global": ModelSpec(
        key="torch-scinet-global",
        description="Torch SCINet-style sample-convolution interaction network (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_scinet_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "num_stages": 3,
            "conv_kernel": 5,
            "ffn_dim": 128,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": MODEL_DIMENSION_PARAM_HELP,
            "num_stages": "Number of SCINet interaction stages",
            "conv_kernel": "Conv1D kernel size (>=1) inside interaction blocks",
            "ffn_dim": "FFN hidden size inside blocks",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-etsformer-global": ModelSpec(
        key="torch-etsformer-global",
        description="Torch ETSformer-style exponential smoothing + Transformer residual model (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_etsformer_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "dim_feedforward": 256,
            "dropout": 0.1,
            "alpha_init": 0.3,
            "beta_init": 0.1,
            "id_emb_dim": 8,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": TRANSFORMER_MODEL_DIMENSION_PARAM_HELP,
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "num_layers": "Transformer encoder layers",
            "dim_feedforward": TRANSFORMER_FFN_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "alpha_init": "Initial smoothing alpha in (0,1) (learned during training)",
            "beta_init": "Initial smoothing beta in (0,1) (learned during training)",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-esrnn-global": ModelSpec(
        key="torch-esrnn-global",
        description="Torch ESRNN-style hybrid (Holt smoothing + RNN residual, lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_esrnn_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "cell": "gru",
            "hidden_size": 64,
            "num_layers": 2,
            "dropout": 0.1,
            "alpha_init": 0.3,
            "beta_init": 0.1,
            "id_emb_dim": 8,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "cell": "RNN cell: gru or lstm",
            "hidden_size": RNN_HIDDEN_SIZE_PARAM_HELP,
            "num_layers": STACKED_RNN_LAYERS_PARAM_HELP,
            "dropout": RNN_DROPOUT_PARAM_HELP,
            "alpha_init": "Initial smoothing alpha in (0,1) (learned during training)",
            "beta_init": "Initial smoothing beta in (0,1) (learned during training)",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-transformer-encdec-global": ModelSpec(
        key="torch-transformer-encdec-global",
        description="Torch encoder-decoder Transformer (lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_transformer_encdec_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "d_model": 64,
            "nhead": 4,
            "num_layers": 2,
            "dim_feedforward": 256,
            "id_emb_dim": 8,
            "dropout": 0.1,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "d_model": TRANSFORMER_MODEL_DIMENSION_PARAM_HELP,
            "nhead": ATTENTION_HEADS_PARAM_HELP,
            "num_layers": "Encoder/decoder layers",
            "dim_feedforward": TRANSFORMER_FFN_DIM_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-nlinear-global": ModelSpec(
        key="torch-nlinear-global",
        description="Torch NLinear-style (last-value centering + linear head, lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_nlinear_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "id_emb_dim": 8,
            "dropout": 0.0,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-dlinear-global": ModelSpec(
        key="torch-dlinear-global",
        description="Torch DLinear-style (moving-average decomposition + linear heads, lite) trained globally across panel series. Requires PyTorch.",
        factory=torch_dlinear_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "ma_window": 7,
            "id_emb_dim": 8,
            "dropout": 0.0,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "ma_window": "Moving-average window size for trend extraction (>=1)",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": DROPOUT_PROBABILITY_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-deepar-global": ModelSpec(
        key="torch-deepar-global",
        description="Torch DeepAR-style global Gaussian RNN (direct multi-horizon, lite). Requires PyTorch.",
        factory=torch_deepar_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "hidden_size": 64,
            "num_layers": 1,
            "id_emb_dim": 8,
            "dropout": 0.0,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "hidden_size": "GRU hidden size",
            "num_layers": "Number of GRU layers",
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "dropout": RNN_DROPOUT_PARAM_HELP,
            "quantiles": "Optional quantiles (computed from Normal params; adds yhat_pXX columns)",
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
            "loss": "Ignored (DeepAR uses Gaussian NLL)",
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-seq2seq-lstm-global": ModelSpec(
        key="torch-seq2seq-lstm-global",
        description="Torch Seq2Seq (encoder-decoder) global model (LSTM, no attention). Requires PyTorch.",
        factory=torch_seq2seq_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "cell": "lstm",
            "attention": "none",
            "hidden_size": 64,
            "num_layers": 1,
            "dropout": 0.0,
            "id_emb_dim": 8,
            "teacher_forcing": 0.5,
            "teacher_forcing_final": None,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "cell": RNN_CELL_PARAM_HELP,
            "attention": ATTENTION_MODE_PARAM_HELP,
            "hidden_size": RNN_HIDDEN_SIZE_PARAM_HELP,
            "num_layers": STACKED_RNN_LAYERS_PARAM_HELP,
            "dropout": RNN_DROPOUT_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "teacher_forcing": TEACHER_FORCING_PARAM_HELP,
            "teacher_forcing_final": TEACHER_FORCING_FINAL_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-seq2seq-gru-global": ModelSpec(
        key="torch-seq2seq-gru-global",
        description="Torch Seq2Seq (encoder-decoder) global model (GRU, no attention). Requires PyTorch.",
        factory=torch_seq2seq_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "cell": "gru",
            "attention": "none",
            "hidden_size": 64,
            "num_layers": 1,
            "dropout": 0.0,
            "id_emb_dim": 8,
            "teacher_forcing": 0.5,
            "teacher_forcing_final": None,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "cell": RNN_CELL_PARAM_HELP,
            "attention": ATTENTION_MODE_PARAM_HELP,
            "hidden_size": RNN_HIDDEN_SIZE_PARAM_HELP,
            "num_layers": STACKED_RNN_LAYERS_PARAM_HELP,
            "dropout": RNN_DROPOUT_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "teacher_forcing": TEACHER_FORCING_PARAM_HELP,
            "teacher_forcing_final": TEACHER_FORCING_FINAL_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-seq2seq-attn-lstm-global": ModelSpec(
        key="torch-seq2seq-attn-lstm-global",
        description="Torch Seq2Seq (encoder-decoder) global model (LSTM + Bahdanau attention). Requires PyTorch.",
        factory=torch_seq2seq_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "cell": "lstm",
            "attention": "bahdanau",
            "hidden_size": 64,
            "num_layers": 1,
            "dropout": 0.0,
            "id_emb_dim": 8,
            "teacher_forcing": 0.5,
            "teacher_forcing_final": None,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "cell": RNN_CELL_PARAM_HELP,
            "attention": ATTENTION_MODE_PARAM_HELP,
            "hidden_size": RNN_HIDDEN_SIZE_PARAM_HELP,
            "num_layers": STACKED_RNN_LAYERS_PARAM_HELP,
            "dropout": RNN_DROPOUT_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "teacher_forcing": TEACHER_FORCING_PARAM_HELP,
            "teacher_forcing_final": TEACHER_FORCING_FINAL_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    "torch-seq2seq-attn-gru-global": ModelSpec(
        key="torch-seq2seq-attn-gru-global",
        description="Torch Seq2Seq (encoder-decoder) global model (GRU + Bahdanau attention). Requires PyTorch.",
        factory=torch_seq2seq_global_forecaster,
        default_params={
            "context_length": 96,
            "x_cols": (),
            "add_time_features": True,
            "sample_step": 1,
            "cell": "gru",
            "attention": "bahdanau",
            "hidden_size": 64,
            "num_layers": 1,
            "dropout": 0.0,
            "id_emb_dim": 8,
            "teacher_forcing": 0.5,
            "teacher_forcing_final": None,
            "quantiles": (),
            "max_train_size": None,
            **_TORCH_COMMON_DEFAULTS,
            "epochs": 30,
            "batch_size": 64,
            "val_split": 0.1,
        },
        param_help={
            "context_length": CONTEXT_LENGTH_PARAM_HELP,
            "x_cols": OPTIONAL_X_COLS_PARAM_HELP,
            "add_time_features": ADD_TIME_FEATURES_PARAM_HELP,
            "sample_step": SAMPLE_STEP_PARAM_HELP,
            "cell": RNN_CELL_PARAM_HELP,
            "attention": ATTENTION_MODE_PARAM_HELP,
            "hidden_size": RNN_HIDDEN_SIZE_PARAM_HELP,
            "num_layers": STACKED_RNN_LAYERS_PARAM_HELP,
            "dropout": RNN_DROPOUT_PARAM_HELP,
            "id_emb_dim": ID_EMB_DIM_PARAM_HELP,
            "teacher_forcing": TEACHER_FORCING_PARAM_HELP,
            "teacher_forcing_final": TEACHER_FORCING_FINAL_PARAM_HELP,
            "quantiles": QUANTILES_PARAM_HELP,
            "max_train_size": MAX_TRAIN_SIZE_PARAM_HELP,
            **_TORCH_COMMON_PARAM_HELP,
        },
        requires=("torch",),
        interface="global",
    ),
    }

